name: Run Node.js App with FFmpeg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the version of Node.js you want to use

    # Install FFmpeg
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    # Install npm dependencies
    - name: Install npm dependencies
      run: |
        npm install
        node .
